package org.locationtech.spatial4j.shape.impl;

import org.junit.Test;
import org.locationtech.spatial4j.context.SpatialContext;
import org.locationtech.spatial4j.shape.Point;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * This class contains tests for the {@link BufferedLine} constructor.
 * Note: This is an improved version of a test originally generated by EvoSuite.
 */
public class BufferedLine_ESTestTest55 extends BufferedLine_ESTest_scaffolding {

    /**
     * Tests that the BufferedLine constructor throws a RuntimeException
     * when created with a point that has an invalid coordinate for a geographic context.
     * Specifically, this test uses a point with a Y-coordinate of positive infinity,
     * which is an invalid latitude.
     */
    @Test(timeout = 4000)
    public void constructorShouldThrowExceptionForInvalidGeographicPoint() {
        // Arrange
        // Use the geographic spatial context, which has world bounds (-180 to 180, -90 to 90).
        SpatialContext geoContext = SpatialContext.GEO;

        // Create a point with an infinite Y-coordinate, which is an invalid latitude.
        Point pointWithInvalidLatitude = new PointImpl(2.0, Double.POSITIVE_INFINITY, geoContext);
        double bufferDistance = 2.0;

        // Act & Assert
        try {
            // Attempt to create a buffered line with the invalid point.
            // This is expected to fail during the bounding box calculation inside the constructor.
            new BufferedLine(pointWithInvalidLatitude, pointWithInvalidLatitude, bufferDistance, geoContext);
            fail("Expected a RuntimeException due to the invalid latitude, but none was thrown.");
        } catch (RuntimeException e) {
            // Verify that the exception message indicates a coordinate validation error.
            // The underlying ShapeFactory rejects coordinates outside the valid latitude range [-90, 90].
            String expectedMessageContent = "maxY must be >= minY";
            assertTrue(
                    "The exception message should complain about invalid Y coordinates.",
                    e.getMessage().contains(expectedMessageContent)
            );
        }
    }
}