package org.apache.commons.collections4.set;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.stream.Stream;
import org.apache.commons.collections4.Closure;
import org.apache.commons.collections4.Equator;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.AnyPredicate;
import org.apache.commons.collections4.functors.ChainedClosure;
import org.apache.commons.collections4.functors.ConstantTransformer;
import org.apache.commons.collections4.functors.DefaultEquator;
import org.apache.commons.collections4.functors.EqualPredicate;
import org.apache.commons.collections4.functors.ExceptionPredicate;
import org.apache.commons.collections4.functors.FalsePredicate;
import org.apache.commons.collections4.functors.IdentityPredicate;
import org.apache.commons.collections4.functors.IfClosure;
import org.apache.commons.collections4.functors.NonePredicate;
import org.apache.commons.collections4.functors.NotNullPredicate;
import org.apache.commons.collections4.functors.NotPredicate;
import org.apache.commons.collections4.functors.NullIsExceptionPredicate;
import org.apache.commons.collections4.functors.NullIsTruePredicate;
import org.apache.commons.collections4.functors.OnePredicate;
import org.apache.commons.collections4.functors.OrPredicate;
import org.apache.commons.collections4.functors.TransformerClosure;
import org.apache.commons.collections4.functors.TruePredicate;
import org.apache.commons.collections4.functors.UniquePredicate;
import org.apache.commons.collections4.functors.WhileClosure;
import org.apache.commons.collections4.iterators.IteratorChain;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

public class CompositeSet_ESTestTest10 extends CompositeSet_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        CompositeSet<LinkedHashSet<Integer>> compositeSet0 = new CompositeSet<LinkedHashSet<Integer>>();
        assertNotNull(compositeSet0);
        LinkedHashSet<Integer> linkedHashSet0 = new LinkedHashSet<Integer>();
        assertNotNull(linkedHashSet0);
        assertTrue(linkedHashSet0.isEmpty());
        assertEquals(0, linkedHashSet0.size());
        Integer integer0 = new Integer((-1));
        assertNotNull(integer0);
        assertEquals((-1), (int) integer0);
        boolean boolean0 = linkedHashSet0.add(integer0);
        assertTrue(linkedHashSet0.contains(integer0));
        assertFalse(linkedHashSet0.isEmpty());
        assertEquals(1, linkedHashSet0.size());
        assertTrue(boolean0);
        CompositeSet<Integer> compositeSet1 = new CompositeSet<Integer>(linkedHashSet0);
        assertNotNull(compositeSet1);
        assertTrue(linkedHashSet0.contains(integer0));
        assertTrue(compositeSet1.contains(integer0));
        assertFalse(linkedHashSet0.isEmpty());
        assertEquals(1, linkedHashSet0.size());
        List<Set<Integer>> list0 = compositeSet1.getSets();
        assertNotNull(list0);
        assertTrue(linkedHashSet0.contains(integer0));
        assertTrue(compositeSet1.contains(integer0));
        assertFalse(linkedHashSet0.isEmpty());
        assertEquals(1, linkedHashSet0.size());
        assertEquals(1, list0.size());
        assertFalse(list0.isEmpty());
        boolean boolean1 = compositeSet1.isEmpty();
        assertTrue(linkedHashSet0.contains(integer0));
        assertTrue(compositeSet1.contains(integer0));
        assertFalse(linkedHashSet0.isEmpty());
        assertEquals(1, linkedHashSet0.size());
        assertFalse(boolean1 == boolean0);
        assertFalse(boolean1);
        CompositeSet<Integer> compositeSet2 = new CompositeSet<Integer>(compositeSet1);
        assertNotNull(compositeSet2);
        assertTrue(linkedHashSet0.contains(integer0));
        assertTrue(compositeSet1.contains(integer0));
        assertTrue(compositeSet2.contains(integer0));
        assertFalse(linkedHashSet0.isEmpty());
        assertEquals(1, linkedHashSet0.size());
        assertTrue(compositeSet2.equals((Object) compositeSet1));
        boolean boolean2 = compositeSet2.retainAll(list0);
        assertNotSame(compositeSet1, compositeSet2);
        assertNotSame(compositeSet2, compositeSet1);
        assertFalse(linkedHashSet0.contains(integer0));
        assertFalse(compositeSet1.contains(integer0));
        assertFalse(compositeSet2.contains(integer0));
        assertTrue(linkedHashSet0.isEmpty());
        assertEquals(0, linkedHashSet0.size());
        assertEquals(1, list0.size());
        assertFalse(list0.isEmpty());
        assertTrue(compositeSet1.equals((Object) compositeSet2));
        assertTrue(compositeSet2.equals((Object) compositeSet1));
        assertTrue(boolean2 == boolean0);
        assertFalse(boolean2 == boolean1);
        assertTrue(boolean2);
        Set<Integer>[] setArray0 = (Set<Integer>[]) Array.newInstance(Set.class, 3);
        setArray0[0] = (Set<Integer>) linkedHashSet0;
        setArray0[1] = (Set<Integer>) linkedHashSet0;
        setArray0[2] = (Set<Integer>) compositeSet2;
        CompositeSet<Integer> compositeSet3 = new CompositeSet<Integer>(setArray0);
        assertEquals(3, setArray0.length);
        assertNotNull(compositeSet3);
        assertFalse(compositeSet3.contains(integer0));
        assertTrue(compositeSet3.equals((Object) compositeSet2));
        assertTrue(compositeSet3.equals((Object) compositeSet1));
        Set<Integer> set0 = compositeSet1.toSet();
        assertNotNull(set0);
        assertNotSame(compositeSet1, compositeSet2);
        assertNotSame(compositeSet1, compositeSet3);
        assertFalse(linkedHashSet0.contains(integer0));
        assertFalse(compositeSet1.contains(integer0));
        assertFalse(set0.contains(integer0));
        assertTrue(linkedHashSet0.isEmpty());
        assertEquals(0, linkedHashSet0.size());
        assertTrue(set0.isEmpty());
        assertEquals(0, set0.size());
        assertTrue(compositeSet1.equals((Object) compositeSet3));
        assertTrue(compositeSet1.equals((Object) compositeSet2));
        boolean boolean3 = compositeSet2.isEmpty();
        assertNotSame(compositeSet1, compositeSet2);
        assertNotSame(compositeSet1, compositeSet3);
        assertNotSame(compositeSet2, compositeSet3);
        assertNotSame(compositeSet2, compositeSet1);
        assertFalse(linkedHashSet0.contains(integer0));
        assertFalse(compositeSet1.contains(integer0));
        assertFalse(compositeSet2.contains(integer0));
        assertTrue(linkedHashSet0.isEmpty());
        assertEquals(0, linkedHashSet0.size());
        assertTrue(compositeSet1.equals((Object) compositeSet3));
        assertTrue(compositeSet1.equals((Object) compositeSet2));
        assertTrue(compositeSet2.equals((Object) compositeSet3));
        assertTrue(compositeSet2.equals((Object) compositeSet1));
        assertTrue(boolean3 == boolean0);
        assertFalse(boolean3 == boolean1);
        assertTrue(boolean3 == boolean2);
        assertTrue(boolean3);
    }
}
