/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 06 10:25:08 GMT 2025
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jsoup.helper.CookieUtil;
import org.jsoup.helper.HttpConnection;
import org.jsoup.nodes.Attributes;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CookieUtil_ESTest extends CookieUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      URI uRI0 = CookieUtil.asUri(uRL0);
      assertNull(uRI0.getRawQuery());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      // Undeclared exception!
      try { 
        CookieUtil.storeCookies(httpConnection_Request0, httpConnection_Response0, (URL) null, (Map<String, List<String>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URL uRL0 = MockURL.getFtpExample();
      // Undeclared exception!
      try { 
        CookieUtil.storeCookies(httpConnection_Request0, (HttpConnection.Response) null, uRL0, (Map<String, List<String>>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument is null
         //
         verifyException("java.net.CookieManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        CookieUtil.parseCookie("Set-Cookie", (HttpConnection.Response) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.CookieUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockFile mockFile0 = new MockFile("vnb'xy>7#JQ4_gZn");
      URL uRL0 = mockFile0.toURL();
      try { 
        CookieUtil.asUri(uRL0);
        fail("Expecting exception: MalformedURLException");
      
      } catch(MalformedURLException e) {
         //
         // Illegal character in path at index 57: file:/Users/tenghaha/Desktop/EvoSuiteProject/jsoup/vnb'xy>7#JQ4_gZn
         //
         verifyException("org.jsoup.helper.CookieUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        CookieUtil.asUri((URL) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("", "|noixdm3!");
      Map<String, String> map0 = attributes1.dataset();
      httpConnection_Request0.cookies = map0;
      // Undeclared exception!
      try { 
        CookieUtil.applyCookiesToRequest(httpConnection_Request0, (BiConsumer<String, String>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        CookieUtil.applyCookiesToRequest((HttpConnection.Request) null, (BiConsumer<String, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.CookieUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CookieUtil.parseCookie("", (HttpConnection.Response) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CookieUtil.parseCookie((String) null, (HttpConnection.Response) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      URL uRL0 = MockURL.getFtpExample();
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("9&{v4vgAJcV4T11n-");
      hashMap0.put("set-cookie", linkedList0);
      CookieUtil.storeCookies(httpConnection_Request0, httpConnection_Response0, uRL0, hashMap0);
      assertEquals("ftp://ftp.someFakeButWellFormedURL.org/fooExample", uRL0.toExternalForm());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URL uRL0 = MockURL.getHttpExample();
      Map<String, List<String>> map0 = httpConnection_Request0.headers;
      CookieUtil.storeCookies(httpConnection_Request0, (HttpConnection.Response) null, uRL0, map0);
      assertEquals(2097152, httpConnection_Request0.maxBodySize());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      Map<String, String> map0 = httpConnection_Request0.cookies;
      httpConnection_Response0.cookies = map0;
      CookieUtil.parseCookie("org.jsoup.helper.CookieUtil", httpConnection_Response0);
      BiConsumer<String, String> biConsumer0 = (BiConsumer<String, String>) mock(BiConsumer.class, new ViolatedAssumptionAnswer());
      CookieUtil.applyCookiesToRequest(httpConnection_Request0, biConsumer0);
      assertEquals(30000, httpConnection_Request0.timeout());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CookieUtil cookieUtil0 = new CookieUtil();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      BiConsumer<String, String> biConsumer0 = (BiConsumer<String, String>) mock(BiConsumer.class, new ViolatedAssumptionAnswer());
      CookieUtil.applyCookiesToRequest(httpConnection_Request0, biConsumer0);
      assertTrue(httpConnection_Request0.followRedirects());
  }
}
