package org.jfree.chart.block;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import java.awt.SystemColor;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.jfree.chart.api.HorizontalAlignment;
import org.jfree.chart.api.RectangleAnchor;
import org.jfree.chart.api.VerticalAlignment;
import org.jfree.chart.text.TextBlockAnchor;
import org.jfree.data.Range;
import org.jfree.data.time.TimePeriodAnchor;
import org.jfree.data.time.TimeSeries;
import org.junit.runner.RunWith;

public class GridArrangement_ESTestTest8 extends GridArrangement_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        GridArrangement gridArrangement0 = new GridArrangement(59, 59);
        assertNotNull(gridArrangement0);
        BlockContainer blockContainer0 = new BlockContainer();
        assertEquals(0.0, blockContainer0.getHeight(), 0.01);
        assertNull(blockContainer0.getID());
        assertEquals(0.0, blockContainer0.getContentYOffset(), 0.01);
        assertEquals(0.0, blockContainer0.getWidth(), 0.01);
        assertEquals(0.0, blockContainer0.getContentXOffset(), 0.01);
        assertTrue(blockContainer0.isEmpty());
        assertNotNull(blockContainer0);
        blockContainer0.add((Block) blockContainer0);
        assertEquals(0.0, blockContainer0.getHeight(), 0.01);
        assertFalse(blockContainer0.isEmpty());
        assertNull(blockContainer0.getID());
        assertEquals(0.0, blockContainer0.getContentYOffset(), 0.01);
        assertEquals(0.0, blockContainer0.getWidth(), 0.01);
        assertEquals(0.0, blockContainer0.getContentXOffset(), 0.01);
        SystemColor systemColor0 = SystemColor.inactiveCaption;
        assertEquals(128, systemColor0.getBlue());
        assertEquals(128, systemColor0.getRed());
        assertEquals((-8355712), systemColor0.getRGB());
        assertEquals(1, systemColor0.getTransparency());
        assertEquals(128, systemColor0.getGreen());
        assertEquals(255, systemColor0.getAlpha());
        assertNotNull(systemColor0);
        ColorBlock colorBlock0 = new ColorBlock(systemColor0, (-1.0), 306.1);
        assertEquals(128, systemColor0.getBlue());
        assertEquals(128, systemColor0.getRed());
        assertEquals((-8355712), systemColor0.getRGB());
        assertEquals(1, systemColor0.getTransparency());
        assertEquals(128, systemColor0.getGreen());
        assertEquals(255, systemColor0.getAlpha());
        assertEquals(0.0, colorBlock0.getContentXOffset(), 0.01);
        assertEquals((-1.0), colorBlock0.getWidth(), 0.01);
        assertEquals(306.1, colorBlock0.getHeight(), 0.01);
        assertNull(colorBlock0.getID());
        assertEquals(0.0, colorBlock0.getContentYOffset(), 0.01);
        assertNotNull(colorBlock0);
        Object object0 = new Object();
        assertNotNull(object0);
        blockContainer0.add((Block) colorBlock0, object0);
        assertEquals(0.0, blockContainer0.getHeight(), 0.01);
        assertFalse(blockContainer0.isEmpty());
        assertNull(blockContainer0.getID());
        assertEquals(0.0, blockContainer0.getContentYOffset(), 0.01);
        assertEquals(0.0, blockContainer0.getWidth(), 0.01);
        assertEquals(0.0, blockContainer0.getContentXOffset(), 0.01);
        assertEquals(128, systemColor0.getBlue());
        assertEquals(128, systemColor0.getRed());
        assertEquals((-8355712), systemColor0.getRGB());
        assertEquals(1, systemColor0.getTransparency());
        assertEquals(128, systemColor0.getGreen());
        assertEquals(255, systemColor0.getAlpha());
        assertEquals(0.0, colorBlock0.getContentXOffset(), 0.01);
        assertEquals((-1.0), colorBlock0.getWidth(), 0.01);
        assertEquals(306.1, colorBlock0.getHeight(), 0.01);
        assertNull(colorBlock0.getID());
        assertEquals(0.0, colorBlock0.getContentYOffset(), 0.01);
        RectangleConstraint rectangleConstraint0 = RectangleConstraint.NONE;
        assertEquals(0.0, rectangleConstraint0.getHeight(), 0.01);
        assertEquals(LengthConstraintType.NONE, rectangleConstraint0.getHeightConstraintType());
        assertEquals(LengthConstraintType.NONE, rectangleConstraint0.getWidthConstraintType());
        assertEquals(0.0, rectangleConstraint0.getWidth(), 0.01);
        assertNotNull(rectangleConstraint0);
        Size2D size2D0 = gridArrangement0.arrange(blockContainer0, (Graphics2D) null, rectangleConstraint0);
        assertEquals(0.0, blockContainer0.getHeight(), 0.01);
        assertFalse(blockContainer0.isEmpty());
        assertNull(blockContainer0.getID());
        assertEquals(0.0, blockContainer0.getContentYOffset(), 0.01);
        assertEquals(0.0, blockContainer0.getWidth(), 0.01);
        assertEquals(0.0, blockContainer0.getContentXOffset(), 0.01);
        assertEquals(0.0, rectangleConstraint0.getHeight(), 0.01);
        assertEquals(LengthConstraintType.NONE, rectangleConstraint0.getHeightConstraintType());
        assertEquals(LengthConstraintType.NONE, rectangleConstraint0.getWidthConstraintType());
        assertEquals(0.0, rectangleConstraint0.getWidth(), 0.01);
        assertEquals(0.0, size2D0.getWidth(), 0.01);
        assertEquals(18059.9, size2D0.getHeight(), 0.01);
        assertEquals("Size2D[width=0.0, height=18059.9]", size2D0.toString());
        assertNotNull(size2D0);
        assertEquals(0.0, size2D0.width, 0.01);
        assertEquals(18059.9, size2D0.height, 0.01);
    }
}
