package org.joda.time;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

/**
 * Tests for {@link IllegalFieldValueException}.
 */
public class IllegalFieldValueExceptionTest {

    @Test
    public void prependMessage_withEmptyStringToAnExistingMessage_shouldAddLeadingColonSeparator() {
        // Arrange: Create an exception with an empty field name and null values,
        // which results in a specific base message format.
        String emptyFieldName = "";
        IllegalFieldValueException exception = new IllegalFieldValueException(
            emptyFieldName,
            (Number) null,
            (Number) null,
            (Number) null
        );
        
        // The initial message generated by the constructor is "Value null for  is not supported".
        // We will now test prepending an empty string to this message.
        String messageToPrepend = "";

        // Act: Prepend the empty message string.
        exception.prependMessage(messageToPrepend);

        // Assert: The new message should consist of the prepended string, a colon-space
        // separator, and the original message. Since the prepended string is empty,
        // the final message starts with the separator.
        String expectedMessage = ": Value null for  is not supported";
        assertEquals(expectedMessage, exception.getMessage());
    }
}