package org.threeten.extra.chrono;

import org.junit.Test;
import static org.junit.Assert.assertTrue;

/**
 * Tests for the {@link JulianChronology} class, focusing on leap year calculations.
 *
 * Note: The original test class name "JulianChronology_ESTestTest31" and its scaffolding
 * suggest it was generated by a tool. This version uses a more conventional name.
 */
public class JulianChronologyTest {

    /**
     * Tests that a negative year (BC) divisible by 4 is correctly identified as a leap year.
     */
    @Test
    public void isLeapYear_shouldReturnTrue_forNegativeYearDivisibleByFour() {
        // In the proleptic Julian calendar, a year is a leap year if it is divisible by 4.
        // This rule applies to all years, including negative (BC) years.
        // The year -236 is equivalent to 237 BC. Since -236 is divisible by 4,
        // it must be considered a leap year.

        // Arrange
        JulianChronology julianChronology = JulianChronology.INSTANCE;
        long prolepticYear = -236;

        // Act
        boolean isLeap = julianChronology.isLeapYear(prolepticYear);

        // Assert
        assertTrue("Year " + prolepticYear + " should be a leap year in the Julian calendar.", isLeap);
    }
}