/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 18 20:23:00 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.CharBuffer;
import org.apache.commons.lang3.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[3];
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charSequenceArray0[0] = (CharSequence) charBuffer0;
      charSequenceArray0[1] = (CharSequence) "FFFFF15A";
      CharSequence[][] charSequenceArray1 = new CharSequence[8][3];
      charSequenceArray1[0] = charSequenceArray0;
      CharSequence[] charSequenceArray2 = new CharSequence[5];
      charSequenceArray2[0] = (CharSequence) "FFFFF15A";
      charSequenceArray2[1] = (CharSequence) "FFFFF15A";
      charSequenceArray1[1] = charSequenceArray2;
      charSequenceArray1[2] = charSequenceArray0;
      charSequenceArray1[3] = charSequenceArray0;
      charSequenceArray1[4] = charSequenceArray0;
      charSequenceArray1[5] = charSequenceArray0;
      charSequenceArray1[6] = charSequenceArray0;
      charSequenceArray1[7] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
      String string0 = lookupTranslator0.translate((CharSequence) "FFFFFFFF");
      assertEquals("FFFFFFFF", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[3];
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charSequenceArray0[0] = (CharSequence) charBuffer0;
      charSequenceArray0[1] = (CharSequence) "FFFFF15A";
      CharSequence[][] charSequenceArray1 = new CharSequence[8][3];
      charSequenceArray1[0] = charSequenceArray0;
      CharSequence[] charSequenceArray2 = new CharSequence[5];
      charSequenceArray2[0] = (CharSequence) "FFFFF15A";
      charSequenceArray2[1] = (CharSequence) "FFFFF15A";
      charSequenceArray1[1] = charSequenceArray2;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "557");
      int int0 = lookupTranslator0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][7];
      CharSequence[] charSequenceArray1 = new CharSequence[3];
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charSequenceArray1[0] = (CharSequence) charBuffer0;
      charSequenceArray1[1] = (CharSequence) "FFFFF15A";
      charSequenceArray1[2] = (CharSequence) charBuffer0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter(1);
      int int0 = lookupTranslator0.translate(charSequenceArray1[2], 0, (Writer) stringWriter0);
      assertEquals("FFFFF15A", stringWriter0.toString());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][3];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) stringBuffer0, 2955, (Writer) stringWriter0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][9];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      StringWriter stringWriter0 = new StringWriter(1);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][9];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      charSequenceArray1[1] = (CharSequence) stringBuffer0;
      charSequenceArray0[0] = charSequenceArray1;
      charSequenceArray1[0] = (CharSequence) stringBuffer0;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][2];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charSequenceArray1[0] = (CharSequence) charBuffer0;
      charSequenceArray1[1] = (CharSequence) charBuffer0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][0];
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[3];
      char[] charArray0 = new char[2];
      charArray0[1] = '1';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charSequenceArray0[0] = (CharSequence) charBuffer0;
      charSequenceArray0[1] = (CharSequence) "FFFFF15A";
      CharBuffer charBuffer1 = CharBuffer.wrap(charSequenceArray0[0]);
      CharBuffer charBuffer2 = CharBuffer.wrap(charSequenceArray0[1]);
      CharSequence[][] charSequenceArray1 = new CharSequence[4][7];
      charSequenceArray1[0] = charSequenceArray0;
      charSequenceArray1[1] = charSequenceArray0;
      charSequenceArray1[2] = charSequenceArray0;
      charBuffer1.get();
      CharSequence[] charSequenceArray2 = new CharSequence[10];
      charSequenceArray2[0] = (CharSequence) charBuffer1;
      charSequenceArray2[1] = (CharSequence) "FFFFF15A";
      charSequenceArray1[3] = charSequenceArray2;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
      String string0 = lookupTranslator0.translate((CharSequence) charBuffer2);
      assertEquals("FFFFFFFFFF15A5A", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
      StringWriter stringWriter0 = new StringWriter(7);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) null, 7, (Writer) stringWriter0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }
}
