/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 21 16:27:38 GMT 2025
 */

package com.itextpdf.text.pdf;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.itextpdf.text.pdf.MappedRandomAccessFile;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MappedRandomAccessFile_ESTest extends MappedRandomAccessFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MappedRandomAccessFile mappedRandomAccessFile0 = new MappedRandomAccessFile("rw", "rw");
      assertEquals(0L, mappedRandomAccessFile0.getFilePointer());
      
      mappedRandomAccessFile0.seek((-1934028355));
      int int0 = mappedRandomAccessFile0.read((byte[]) null, (-1934028355), (-1458));
      assertEquals((-1), int0);
  }

  // ... (and 22 other cryptic tests)
}