/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 19 13:46:36 GMT 2025
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.FormElement;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.NodeIterator;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NodeIterator_ESTest extends NodeIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("org.jsouphnodes.NodeIterator", "org.jsouphnodes.NodeIterator");
      NodeIterator<Node> nodeIterator0 = NodeIterator.from(document0);
      nodeIterator0.next();
      Node node0 = nodeIterator0.next();
      assertTrue(node0.hasParent());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("org.jsoup.nodes.NodeIterator", "org.jsoup.nodes.NodeIterator");
      NodeIterator<Node> nodeIterator0 = NodeIterator.from(document0);
      boolean boolean0 = nodeIterator0.hasNext();
      assertTrue(boolean0);
  }

  // ... (rest of the original, hard-to-read tests)
}