package org.apache.commons.lang3;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

/**
 * Unit tests for the {@link RandomUtils} class.
 */
public class RandomUtilsTest {

    /**
     * Tests that {@link RandomUtils#randomBytes(int)} returns a byte array of the
     * specified length when using an insecure random instance.
     */
    @Test
    public void randomBytes_usingInsecureInstance_returnsArrayOfCorrectLength() {
        // Arrange
        final int expectedSize = 404;
        // Get an insecure RandomUtils instance, which uses ThreadLocalRandom.
        final RandomUtils randomUtils = RandomUtils.insecure();

        // Act
        final byte[] resultBytes = randomUtils.randomBytes(expectedSize);

        // Assert
        assertNotNull("The generated byte array should not be null.", resultBytes);
        assertEquals("The generated byte array should have the specified length.", expectedSize, resultBytes.length);
    }
}